---
title: "sports betting exploration"
output: github_document
date: "2025-11-13"
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Look at total handle

```{r}
sb_rev_month_df = read_csv('./data/legal_sports_report/sb_rev_by_month.csv')
state_legal_df = read_csv('./data/legal_sports_report/state_legalization_dates.csv')

get_n_states_legal = function(input_month) {
  n_states_legal = nrow(filter(state_legal_df, first_start <= input_month))
}

sb_rev_month_df = sb_rev_month_df |> 
  mutate(
    n_states_legal = sapply(month, get_n_states_legal)
  ) 

sb_rev_month_df |> 
  ggplot(aes(x = month, y=handle)) +
  geom_line() 

scale_factor = max(sb_rev_month_df$n_states_legal) / max(sb_rev_month_df$handle)

sb_rev_month_df |> 
  ggplot(aes(x = month)) +
  geom_line(aes(y=handle, color="handle")) +
  geom_line(aes(y=n_states_legal / scale_factor, color="legal")) +
  scale_y_continuous(
    name = "Handle",
    sec.axis = sec_axis(~ . * scale_factor, name="States Legal")
  )
```



